import React from 'react';
import PublicLayout from '../../components/PublicLayout';

export default function Disclaimer() {
  return (
    <PublicLayout>
      <div className="py-16 bg-light-surface">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-text-primary mb-2">Disclaimer</h1>
          <p className="text-text-secondary mb-8">Last updated: December 2024</p>

          <div className="prose prose-slate max-w-none">
            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">1. General Information</h2>
              <p className="text-text-secondary mb-4">
                The information provided by SkatalystAI ("we", "us", or "our") on our platform
                is for general informational purposes only. All information on the platform is
                provided in good faith, however we make no representation or warranty of any kind,
                express or implied, regarding the accuracy, adequacy, validity, reliability,
                availability, or completeness of any information on the platform.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">2. AI-Generated Content</h2>
              <p className="text-text-secondary mb-4">
                SkatalystAI uses artificial intelligence to analyze and organize data. While we
                strive for accuracy, AI-generated outputs may contain errors, inaccuracies, or
                inappropriate categorizations. You should:
              </p>
              <ul className="list-disc list-inside text-text-secondary space-y-2">
                <li>Review all AI-generated outputs before use</li>
                <li>Not rely solely on AI analysis for critical decisions</li>
                <li>Verify important categorizations and relationships manually</li>
                <li>Use professional judgment when implementing suggestions</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">3. No Professional Advice</h2>
              <p className="text-text-secondary mb-4">
                The platform does not provide legal, financial, medical, or other professional advice.
                Any data organization suggestions, database schemas, or structural recommendations
                are provided as technical guidance only and should not be considered professional advice.
              </p>
              <p className="text-text-secondary mb-4">
                Before making decisions based on our platform's output, consult with qualified
                professionals as appropriate for your specific situation.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">4. Data Accuracy</h2>
              <p className="text-text-secondary mb-4">
                While we employ advanced AI models and algorithms, we cannot guarantee:
              </p>
              <ul className="list-disc list-inside text-text-secondary space-y-2">
                <li>100% accuracy in theme detection or categorization</li>
                <li>Complete identification of all duplicates or relationships</li>
                <li>Error-free database schema generation</li>
                <li>Perfect alignment with your specific business requirements</li>
              </ul>
              <p className="text-text-secondary mt-4">
                Users are responsible for validating all outputs before implementation in
                production environments.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">5. Generated Code and Artifacts</h2>
              <p className="text-text-secondary mb-4">
                Any code, schemas, scripts, or other technical artifacts generated by SkatalystAI:
              </p>
              <ul className="list-disc list-inside text-text-secondary space-y-2">
                <li>Are provided "as-is" without warranty</li>
                <li>May require modification for your specific use case</li>
                <li>Should be reviewed for security vulnerabilities before deployment</li>
                <li>Are your responsibility to test, maintain, and secure</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">6. External Links</h2>
              <p className="text-text-secondary mb-4">
                Our platform may contain links to external websites or services that are not
                owned or controlled by SkatalystAI. We have no control over, and assume no
                responsibility for, the content, privacy policies, or practices of any third-party
                sites or services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">7. Service Availability</h2>
              <p className="text-text-secondary mb-4">
                We do not guarantee that the platform will be available at all times or that it
                will be free from errors or interruptions. We reserve the right to modify, suspend,
                or discontinue any part of the service at any time without prior notice.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">8. Limitation of Liability</h2>
              <p className="text-text-secondary mb-4">
                Under no circumstances shall SkatalystAI be liable for any direct, indirect,
                incidental, consequential, special, or exemplary damages arising out of or in
                connection with your use of the platform, including but not limited to:
              </p>
              <ul className="list-disc list-inside text-text-secondary space-y-2">
                <li>Loss of data or data corruption</li>
                <li>Business interruption or lost profits</li>
                <li>Errors in AI-generated outputs</li>
                <li>Security breaches resulting from generated code</li>
                <li>Any other losses arising from use of our services</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">9. Beta Features</h2>
              <p className="text-text-secondary mb-4">
                Some features may be marked as "Beta" or "Experimental". These features:
              </p>
              <ul className="list-disc list-inside text-text-secondary space-y-2">
                <li>May be unstable or contain bugs</li>
                <li>May be modified or removed without notice</li>
                <li>Are provided for testing purposes only</li>
                <li>Should not be relied upon for production use</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">10. Changes to This Disclaimer</h2>
              <p className="text-text-secondary mb-4">
                We reserve the right to update or modify this disclaimer at any time without
                prior notice. Your continued use of the platform after any changes indicates
                your acceptance of the modified disclaimer.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-text-primary mb-4">11. Contact</h2>
              <p className="text-text-secondary">
                If you have questions about this disclaimer, please contact us at:{' '}
                <a href="mailto:legal@skatalystai.com" className="text-ion hover:opacity-80 transition-opacity">
                  legal@skatalystai.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}
